description: "attraction-repulsion with 3 types particles in 3D"
dataset: "arbitrary_3_3D"

simulation:
  dimension: 3
  params:
    [
      [1.6233, 1.0413, 1.6012, 1.5615],
      [1.7667, 1.8308, 1.0855, 1.9055],
      [1.7226, 1.7850, 1.0584, 1.8579],
    ]
  func_params: [["arbitrary", 0, 0], ["arbitrary", 1, 1], ["arbitrary", 2, 2]]
  min_radius: 0
  max_radius: 0.175
  n_particles: 15000
  n_particle_types: 3
  n_frames: 4000
  sigma: 0.01
  delta_t: 0.1
  dpos_init: 0
  boundary: "periodic"

graph_model:
  particle_model_name: "PDE_A"
  mesh_model_name: ""
  prediction: "first_derivative"
  input_size: 8
  output_size: 3
  hidden_dim: 128
  n_layers: 5
  aggr_type: "mean"
  embedding_dim: 2
  update_type: "none"

plotting:
  colormap: "tab10"
  arrow_length: 2
  ylim: [-0.04, 0.03]

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: False
  n_runs: 1
  sparsity: "replace_embedding_function"
  cluster_method: "distance_plot"
  rotation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: "auto"
